### ISSUE TITLE
Suggestion: world.detach instead of destroy

### ISSUE THREAD

**Issue by rizrmd** [isaac-mason/arancini#242]
The documentation says that world.destroy is not actually destroying the entity, it's just detaching the entity from being queried in the world:

<img width="881" alt="image" src="https://github.com/isaac-mason/arancini/assets/126301/8b7742eb-48ac-4401-a491-2268fceb34ee">

Why not just name it detach ?

**Comment by isaac-mason** [comment]
Hey @rizrmd! I appreciate the suggestion.

I've thought about renaming the main methods to:
- `add` - add an entity to the world
- `remove` - remove an entity from the world
- `addComponent` - add a component to an entity
- `removeComponent` - remove a component from an entity

(basically copying miniplex's names 🙂)

I do like the short names `world.add` and `world.remove`, but at face value `world.create` and `world.add` both sound like they could be used to add an entity to the world. Similar situation with `world.remove` and `world.destroy`.

What do you think?

**Comment by rizrmd** [comment]
That's better than detach!

I'm curious, why create another ecs when miniplex is good enough ?

**Comment by isaac-mason** [comment]
Mostly for fun 🙂 Writing your own ECS is basically a game developer canon event.

**Comment by rizrmd** [comment]
I think I like attach/detach better, because it implies that it is just reusing already existing object, not creating something new/destroying something. IMO it clears ambiguity between add/create.

**Comment by rizrmd** [comment]
And we can create a shortcut method:

add = create + attach.

**Comment by rizrmd** [comment]
Closing this, I hope my input helps to improve arancini!

**Comment by isaac-mason** [comment]
Thanks @rizrmd! 🙂 

I'll let the decision between create/add/attach etc mull for a bit and make it for the next major.
